name: "Publish"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  PROJECT_PATH: VRCMicOverlay/VRCMicOverlay.csproj
  PUBLISH_PATH: VRCMicOverlay/bin/Release/net6.0/win-x64/publish/
  ZIP_PATH: VRCMicOverlay/VRCMicOverlay/bin/Release/net6.0/win-x64/publish/VRCMicOverlay.zip

permissions:
  contents: write

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Initialize Actions
        uses: actions/checkout@v2

      - name: Initialize .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore Project
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Publish Project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Create Zip File
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{ env.PUBLISH_PATH }}"
          filename: "${{ env.ZIP_PATH }}"

      - run: Get-ChildItem -Recurse -Filter 'VRCMicOverlay.zip'

      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          name: "VRCMicOverlay ${{ github.ref }}"
          tag_name: ${{ github.ref }}
          files: ${{ env.ZIP_PATH }}
