name: "Publish"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  PROJECT_PATH: VRCMicOverlay/VRCMicOverlay.csproj
  PUBLISH_PATH: VRCMicOverlay/bin/Release/net6.0/win-x64/publish/VRCMicOverlay.exe
  ZIP_PATH: VRCMicOverlay/VRCMicOverlay/bin/Release/net6.0/win-x64/publish/VRCMicOverlay.zip

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Initialize Actions
        uses: actions/checkout@v2

      - name: Initialize .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Project
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Publish Project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Create Zip File
        uses: papeloto/action-zip@v1
        with:
          files: ${{ env.PUBLISH_PATH }}
          dest: ${{ env.ZIP_PATH }}

      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          name: "VRCMicOverlay ${{ github.ref }}"
          tag_name: ${{ github.ref }}
          files: ${{ env.ZIP_PATH }}
